name: Deploy Node Application

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: self-hosted
        steps:
            - name: Checkout Source
              uses: actions/checkout@v4

            - name: Build Docker Image
              run: docker build -t nodejs-app:latest .

    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Stop and Remove Existing Container
              run: docker rm -f nodejs-app-container || true

            - name: Run Docker Container
              run: |
                  docker run -d \
                    -p 8080:8080 \
                    --name nodejs-app-container \
                    --env-file .env \
                    nodejs-app:latest
