name: Node.js CI/CD

on:
    push:
        branches:
            - main

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            - name: Build Docker image
              run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejs-app:${{ github.sha }} .

            - name: Tag Docker image as latest
              run: docker tag ${{ secrets.DOCKER_USERNAME }}/nodejs-app:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest

            - name: Push Docker image to Docker Hub
              run: |
                  docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-app:${{ github.sha }}
                  docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest

    deploy:
        needs: build-and-push
        runs-on: self-hosted
        steps:
            - name: Login to Docker Hub
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            - name: Stop and remove existing container
              run: docker rm -f nodejs-app-container || true

            - name: Remove old image
              run: docker rmi ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest || true

            - name: Pull latest image from Docker Hub
              run: docker pull ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest

            - name: Run Docker container
              run: |
                  docker run -d \
                    -p 8080:8080 \
                    --name nodejs-app-container \
                    -e PORT=${{ secrets.PORT }} \
                    -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
                    -e REDIS_URL=${{ secrets.REDIS_URL }} \
                    -e SMTP_HOST=${{ secrets.SMTP_HOST }} \
                    -e SMTP_PORT=${{ secrets.SMTP_PORT }} \
                    -e SMTP_SERVICE=${{ secrets.SMTP_SERVICE }} \
                    -e SMTP_MAIL=${{ secrets.SMTP_MAIL }} \
                    -e SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }} \
                    -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
                    -e FRONTEND_URL=${{ secrets.FRONTEND_URL }} \
                    -e RAZORPAY_KEY_ID=${{ secrets.RAZORPAY_KEY_ID }} \
                    -e RAZORPAY_KEY_SECRET=${{ secrets.RAZORPAY_KEY_SECRET }} \
                    -e RAZORPAY_WEBHOOK_SECRET=${{ secrets.RAZORPAY_WEBHOOK_SECRET }} \
                    -e AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }} \
                    -e AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }} \
                    -e AWS_REGION=${{ secrets.AWS_REGION }} \
                    ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest
